### ISSUE TITLE
npm dependencies missing?

### ISSUE THREAD

**Issue by manid** [splunk/dashpub#23]
Hi, currently when installing this specific dependencies are not anymore available in the npm registry?

`npm ERR! 404 Not Found - GET https://registry.npmjs.org/@splunk/visualization-editors/-/visualization-editors-18.2.1.tgz
npm ERR! 404 
npm ERR! 404  '@splunk/visualization-editors@18.2.1' is not in the npm registry.`

same with yarn
`error An unexpected error occurred: "https://registry.yarnpkg.com/@splunk%2fvisualization-editors: Not found". `

**Comment by ryanwoconnor** [comment]
Hi Manid!

I am actively working with the necessary teams inside of Splunk to try and resolve these dependencies. Apologies for the delays on this. I will update this issue once we have this resolved. 

Thank you,
Ryan
